---
name: Bug Report
about: Report a bug to help us improve
title: "[BUG] "
labels: bug
assignees: RakeemRanger
---

## Description
Brief description of the bug.

## Environment
- **Python Version**: 3.11 (or other)
- **Azure Functions Core Tools**: (version)
- **Region**: Sweden Central (or other)
- **Infrastructure**: Bicep deployed on (date)

## Steps to Reproduce
1. Step 1
2. Step 2
3. Step 3

## Expected Behavior
What should happen?

## Actual Behavior
What actually happens?

## Error Logs
```
Paste error message and stack trace here
```

## Screenshots
If applicable, add screenshots showing the issue.

## Related Issues
Link to any related issues: #123

## Root Cause Analysis (if known)
Description of suspected root cause

## Proposed Solution (if known)
Description of potential fix

---
**Note**: Include relevant context:
- Queue name (if queue-related)
- Function trigger type
- Specific agent or tool involved
